server:
  port: 8081
  context-path: /springboot

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


name: B
age: 18
content: "name: ${name}, age: ${age}"

ttt:
  name: 2009
  age: 30
